### ISSUE TITLE
ProxyError

### ISSUE THREAD

**Issue by damnitall** [synackray/vcenter-netbox-sync#17]
**Environment**
CentOS 7.7.1908
Python 3.6.8
NetBox v2.6.9
Proxy needed for anything "internet related". Package name: **cntlm**

**Steps to Reproduce**
Execute run.py
Error gets thrown:
```
2019-12-30 15:15:49,849 [DEBUG] Log level has been overriden by the --verbose argument.
2019-12-30 15:15:49,849 [INFO] Verifying all prerequisite objects exist in NetBox.
2019-12-30 15:15:49,849 [DEBUG] Checking NetBox has necessary manufacturer objects.
2019-12-30 15:15:49,849 [DEBUG] Sending GET to https://xxx.domain.local/api/dcim/manufacturers/?name=VMware
2019-12-30 15:15:59,862 [WARNING] Critical connection error occurred. Skipping sync with 'xxx.domain.local'.
2019-12-30 15:15:59,863 [DEBUG] Connection error details: HTTPSConnectionPool(host='xxx.domain.local', port=443): Max retries exceeded with url: /api/dcim/manufacturers/?name=VMware (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
```

**Additional information**
```
cat settings.py
#!/usr/bin/env python3

# Program Settings
LOG_LEVEL = "info" # Valid options are debug, info, warning, error, critical
LOG_CONSOLE = True # Logs to console if True, disables console logging if False
LOG_FILE = True # Places all logs in a rotating file if True
IPV4_ALLOWED = ["192.168.0.0/16", "172.16.0.0/12", "10.0.0.0/8"] # IPv4 networks eligible to be synced to NetBox
IPV6_ALLOWED = ["fe80::/10"] # IPv6 networks eligible to be synced to NetBox

# vCenter Settings
VC_HOSTS = [
    # Hostname (FQDN or IP) and port used to access vCenter cluster
    # You can add more vCenter instances by duplicating the line below and
    # updating the values
    {"HOST": "aaaaaaaa.domain.local", "PORT": 443},
    ]
VC_USER = "netbox@vsphere.local" # User account to authenticate to vCenter, supports SSO with @domain.tld suffix
VC_PASS = "yyyyyyyyyyyyyy" # Password for the account defined in VC_USER

# NetBox Settings
NB_API_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # NetBox API Key
NB_DISABLE_TLS = False # Disables SSL/TLS and uses HTTP for requests. Not ever recommended.
NB_FQDN = "xxx.domain.local" # The fully qualified domain name to reach NetBox
NB_PORT = 443 # [optional] NetBox port to connect to if changed from the default
NB_PRUNE_ENABLED = True # Automatically orphan and delete objects if they are no longer in their source system
NB_PRUNE_DELAY_DAYS = 0 # How many days should we wait before pruning an orphaned object
```

```
cat /etc/environment
export http_proxy=http://127.0.0.1:3128
export https_proxy=http://127.0.0.1:3128
```

**Troubleshooting**

- removing the proxy in **/etc/environment** did not help
- inserting *127.0.0.1* in **settings.py** did not help
- and half a dozen things i tried but do not remember

However...

As everything is running on the same box i tried *127.0.0.1:8001* on **settings.py** and I got:
```
2019-12-30 15:38:58,427 [DEBUG] Log level has been overriden by the --verbose argument.
2019-12-30 15:38:58,427 [INFO] Verifying all prerequisite objects exist in NetBox.
2019-12-30 15:38:58,427 [DEBUG] Checking NetBox has necessary manufacturer objects.
2019-12-30 15:38:58,427 [DEBUG] Sending GET to http://127.0.0.1:8001/api/dcim/manufacturers/?name=VMware
Traceback (most recent call last):
  File "/venv/netbox-vcenter-sync/run.py", line 1156, in <module>
    main()
  File "/venv/netbox-vcenter-sync/run.py", line 45, in main
    nb.verify_dependencies()
  File "/venv/netbox-vcenter-sync/run.py", line 1096, in verify_dependencies
    self.obj_exists(nb_obj_type=dep_type, vc_data=dep)
  File "/venv/netbox-vcenter-sync/run.py", line 773, in obj_exists
    query=query
  File "/venv/netbox-vcenter-sync/run.py", line 720, in request
    req_type.upper(), req.status_code, data, req.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by synackray** [comment]
Hello @damnitall. Thank you very much for the report, and also thanks for including the cntlm package name. I will review this and get back to you.

**Comment by damnitall** [comment]
update:

i managed to make it work by disabling the proxy:
```
export no_proxy='*'
```

this is not really a solution but... it is an improvement

**Comment by synackray** [comment]
@damnitall Thank you for the update. Unfortunately, I do not have the infrastructure to test cntlm specifically, but I have made an effort to look in to the problem.

It appears this issue is specific to using cntlm as noted [here](https://stackoverflow.com/questions/48283909/using-python-requests-with-cntlm-corporate-proxy). This is further confirmed by the requests [documentation](https://3.python-requests.org/user/advanced/#proxies) which states standard proxies set through environment variables should not require any particular parameters. 

While I don't have the ability to test this, you are welcome to try using the requests-ntlm module to see if it helps.

1. Activate your virtual environment (venv) and run `pip install requests_ntlm`
2. Modify the following two lines in `run.py`:
Towards the top under the line `import requests` add `from requests_ntlm import HttpNtlmAuth`.

Update this section:
```
        if not self.nb_session:
            self.nb_session = requests.Session()
            self.nb_session.headers.update(self.header)
```

To the following, adjusting `domain`, `username`, and `password` for their respective values required for your proxy.
```
        if not self.nb_session:
            self.nb_session = requests.Session()
            self.nb_session.auth = HttpNtlmAuth('domain\\username','password')
            self.nb_session.headers.update(self.header)
```

I cannot patch this into the main application at this time, but if you do find this works for you I will document it. 

Alternatively, I did come across this [StackOverflow post](https://stackoverflow.com/questions/43814526/requests-library-pip-ntlm-proxy-settings-issues-python) that mentions the use of a middle-man proxy to handle the connection, but there are no details and at first glance would seem to be cumbersome. My apologies for the situation.

**Comment by damnitall** [comment]
thank you for your quick answer and for taking the time to troubleshoot this "mess of a setup i have at work".

unfortunately your solution did not work... continues to timeout.

however i found a solution that works fine for me:
```
import os
os.environ['no_proxy'] = '*'
```

these lines added on run.py solved my issues without having to destroy the proxy configuration for the OS :)

PS: Feel free to close the ticket if you want. if you prefer to continue to troubleshoot this issue further i am fine too.

**Comment by synackray** [comment]
Thanks for the solution. I'm sure you're not the only one who will run into this situation. Happy New Year!
