### ISSUE TITLE
Add hypervisor field when VM operate

### ISSUE THREAD

**Issue by inetman28** [synackray/vcenter-netbox-sync#56]
**Is your feature request related to a problem? Please describe.**
Can not determine when VM operate now.

**Describe the solution you'd like**
We can add custom field in netbox named "ESXi HOST" or "HYPERVISOR" and push information about hypervisor name to this field in netbox

**Comment by synackray** [comment]
Hi @inetman28! Is the ask here to be able to create a correlation of what NetBox Device/vCenter Host the virtual machine currently resides on? I very much want this feature too and was hoping this could be accomplished in the upstream NetBox project for the long-term.

In the short-term, would you prefer a custom field, placing the data inside the comments, or config context? I see pros and cons to all options there.

**Comment by inetman28** [comment]
now, we can add custom field for virtual-machine item.
![image](https://user-images.githubusercontent.com/45913745/74007899-87c25680-4990-11ea-9660-c4c6ad21da11.png)
![image](https://user-images.githubusercontent.com/45913745/74007944-a4f72500-4990-11ea-868f-4f051ad20bbe.png)
![image](https://user-images.githubusercontent.com/45913745/74007978-c0fac680-4990-11ea-88cd-4305c23a4f48.png)

and we can see in api

```
GET /api/virtualization/virtual-machines/{virtual_machine_ID}/
```

{
...
    "custom_fields": {
        "Hypervisor": null
    },
...
}

**Comment by synackray** [comment]
Hi @inetman28! I understand the use of a custom field and agree it is an option. Sorry if I was not clear. I was instead saying that I wish the field was built in and not custom. I don't necessarily like making model level changes to a NetBox instance outside my own. 

However, I would see this as valuable and perhaps we can compromise by offering it as an optional feature. I'll start working on it this weekend.

**Comment by synackray** [comment]
@inetman28 I have been playing around with this and no option that leverages custom field leaves me satisfied. There are two major roadblocks.

- Users must be instructed to manually create the custom field desired. There is no API presented to programmatically handle this.
- Users may setup the custom field values in a different order, with altered field name, or different values that are not accounted for. Unlike standardized models, this leads to ambiguity and risk of deviation in setup which will cause the script to fail.

While clear instructions can be provided to try and reduce the risks, and an API call can be made to dynamically learn the state of the custom field, it will remain a feature which offers too much ambiguity and chance of error. In the end, this is a feature that would be better implemented in the upstream NetBox project. However, it should be noted per the NetBox documentation this seems to be an intentional decision as quoted below.

> Physical devices may be associated with clusters as hosts. This allows users to track on which host(s) a particular VM may reside. However, NetBox does not support pinning a specific VM within a cluster to a particular host device.

[Source](https://netbox.readthedocs.io/en/stable/core-functionality/virtual-machines/)

I have tested placing the data inside a local config context with good success. If this is something you may be interested in please let me know and I would be willing to add that functionality. Thanks!
